# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/timesheet_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Security Configuration
jwt.secret=1c9cd5f8c7cc13d3451a48f43faf5f053a9daaffd879c9c75d8c0edeaa92b7ceb5b0e60d62fcc88ed02321054a0ac82848c7606ada410575e0357579c3148be9
jwt.expiration=86400000

# Logging
logging.level.com.timesheet=DEBUG

# CORS Configuration
cors.allowed-origins=http://localhost:4200